DROP TABLE IF EXISTS ANUNCIOS;
CREATE TABLE ANUNCIOS (
ID INT AUTO_INCREMENT PRIMARY KEY,
NOME_ANUNCIO VARCHAR(40),
CLIENTE VARCHAR(50),
DATA_INICIO DATE,
DATA_FIM DATE,
INVESTIMENTO_DIARIO DECIMAL(10.4)

);

